<!--
  SPDX-License-Identifier: MIT
  Copyright (c) 2026 Allan Barcelos. OpenTube: https://github.com/allanbarcelos/opentube
-->

<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\OpenTube.Infrastructure\OpenTube.Infrastructure.csproj" />
    <ProjectReference Include="..\OpenTube.Domain\OpenTube.Domain.csproj" />
    <ProjectReference Include="..\OpenTube.Shared\OpenTube.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
