# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Allan Barcelos. OpenTube: https://github.com/allanbarcelos/opentube

# O Makefile para quem usa PowerShell (Windows, ou pwsh no macOS e no Linux). Os mesmos alvos,
# com os parâmetros do make virando parâmetros do script:
#
#   ./make.ps1                     menu
#   ./make.ps1 watch               dev completo com hot-reload
#   ./make.ps1 test -p Web         make test p=Web
#   ./make.ps1 logs -s app         make logs s=app
#   ./make.ps1 mock -videos 10 -collections 5.3-10
#   ./make.ps1 whisper -m base
#
# No Windows, se a política de execução bloquear o script:
#   pwsh -ExecutionPolicy Bypass -File .\make.ps1 watch
#
# Precisa do PowerShell 7 (pwsh): o 'watch' encerra a árvore de processos do dotnet watch.

#Requires -Version 7.2

[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [string] $Target = 'help',

    # Serviço do docker compose (restart, logs, shell).
    [string] $s,

    # Projeto de testes: Domain, Infrastructure, Worker ou Web.
    [string] $p,

    # Catálogo de exemplo do 'mock'.
    [string] $videos,
    [string] $collections,
    [string] $colections,

    # Modelo do 'whisper'.
    [string] $m
)

$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot

$DevDeps       = @('postgres', 'minio', 'mailpit')
$ComposeDev    = @('-f', 'docker-compose.yml', '-f', 'docker-compose.dev.yml')
$TestArtifacts = '.artifacts/test'

# ── Utilitários ───────────────────────────────────────────────────────────────

# Roda um programa e para o script se ele falhar, como o make faz com cada linha.
function Invoke-Checked {
    param([string] $Program, [string[]] $Arguments)

    & $Program @Arguments
    if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
    }
}

function Test-Command([string] $Name) {
    [bool](Get-Command $Name -ErrorAction SilentlyContinue)
}

function Fail([string] $Message) {
    Write-Host "  $Message" -ForegroundColor Red
    exit 1
}

# Segredo aleatório só com letras e dígitos, como o gen-env.sh.
function New-Secret([int] $Length) {
    $alfabeto = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
    $bytes = [System.Security.Cryptography.RandomNumberGenerator]::GetBytes($Length)
    -join ($bytes | ForEach-Object { $alfabeto[$_ % $alfabeto.Length] })
}

function New-Hex([int] $Bytes) {
    [Convert]::ToHexString([System.Security.Cryptography.RandomNumberGenerator]::GetBytes($Bytes)).ToLowerInvariant()
}

# ── Bootstrap ─────────────────────────────────────────────────────────────────

# O .env com usuário, senha e chaves aleatórios. Se já existe, fica como está: o PostgreSQL só
# aceita a senha da primeira inicialização do volume.
function Initialize-Env {
    $destino = Join-Path $PSScriptRoot '.env'

    if (Test-Path $destino) {
        return
    }

    $admin = if ($env:OPENTUBE_ADMIN_EMAIL) { $env:OPENTUBE_ADMIN_EMAIL } else { 'admin@localhost' }

    $conteudo = @(
        '# Generated by make.ps1. Do not commit.'
        "POSTGRES_DB=db_$(New-Hex 5)"
        "POSTGRES_USER=user_$(New-Hex 4)"
        "POSTGRES_PASSWORD=$(New-Secret 32)"
        "MINIO_ROOT_USER=minio_$(New-Hex 4)"
        "MINIO_ROOT_PASSWORD=$(New-Secret 32)"
        "TOKEN_PEPPER=$(New-Secret 48)"
        "IP_HASH_PEPPER=$(New-Secret 48)"
        'OPENTUBE_HOST=localhost'
        "OPENTUBE_ADMIN_EMAIL=$admin"
    )

    # Sem BOM e com LF: o docker compose lê o mesmo arquivo.
    [System.IO.File]::WriteAllText($destino, ($conteudo -join "`n") + "`n")

    # Só para quem o criou, como o modo 600 do gen-env.sh.
    if ($IsWindows) {
        & icacls $destino /inheritance:r /grant:r "$($env:USERNAME):(R,W)" | Out-Null
    } else {
        & chmod 600 $destino
    }

    Write-Host '  .env created with a random user, password, and keys.'
    Write-Host '  The file stays on this machine only. It is not printed again.'
}

# Lê o .env e define as variáveis que a aplicação lê no host, como o scripts/dev-env.sh.
function Import-DevEnv {
    if (-not (Test-Path .env)) {
        Fail 'Missing .env. Run ./make.ps1 deps-up.'
    }

    $valores = @{}
    foreach ($linha in Get-Content .env) {
        if ($linha -match '^\s*(#|$)') { continue }
        if ($linha -notmatch '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$') { continue }

        $valor = $Matches[2].Trim()
        if ($valor -match '^"(.*)"$' -or $valor -match "^'(.*)'$") {
            $valor = $Matches[1]
        }

        $valores[$Matches[1]] = $valor
        Set-Item "env:$($Matches[1])" $valor
    }

    $conexao = "Host=localhost;Port=5432;Database=$($valores.POSTGRES_DB);Username=$($valores.POSTGRES_USER);Password=$($valores.POSTGRES_PASSWORD)"

    $env:ConnectionStrings__Default = $conexao
    $env:OPENTUBE_DB                = $conexao
    $env:Storage__Endpoint          = 'http://localhost:9000'
    $env:Storage__AccessKey         = $valores.MINIO_ROOT_USER
    $env:Storage__SecretKey         = $valores.MINIO_ROOT_PASSWORD
    $env:Security__TokenPepper      = $valores.TOKEN_PEPPER
    $env:Security__IpHashPepper     = $valores.IP_HASH_PEPPER
    $env:Security__PublicUrl        = 'http://localhost:5080'
    # O administrador do desenvolvimento vem do .env de cada máquina, e não de um arquivo do
    # repositório: o appsettings.Development.json vai dentro da imagem publicada.
    $env:Security__AdminEmails__0   = if ($valores.OPENTUBE_ADMIN_EMAIL) { $valores.OPENTUBE_ADMIN_EMAIL } else { 'admin@localhost' }
    if (-not $env:ASPNETCORE_ENVIRONMENT) { $env:ASPNETCORE_ENVIRONMENT = 'Development' }
    if (-not $env:DOTNET_ENVIRONMENT)     { $env:DOTNET_ENVIRONMENT     = 'Development' }

    # Transcrição automática de legendas: ligada quando o whisper-cli e o modelo baixado pelo
    # 'whisper' existem. Uma configuração já definida no ambiente prevalece.
    if (-not $env:Transcription__Executable -and (Test-Command whisper-cli) -and (Test-Path .whisper/modelo.bin)) {
        $env:Transcription__Executable = (Get-Command whisper-cli).Source
        $env:Transcription__ModelPath   = Join-Path $PSScriptRoot '.whisper/modelo.bin'
    }
}

# Docker no ar; no macOS, sobe o Colima se ele existir.
function Assert-Docker {
    if (-not (Test-Command docker)) {
        Fail 'Docker não encontrado no PATH. Instale o Docker Desktop (ou o Colima, no macOS).'
    }

    & docker info *> $null
    if ($LASTEXITCODE -eq 0) {
        return
    }

    if (Test-Command colima) {
        Write-Host '  Docker não está rodando. Iniciando Colima...'
        Invoke-Checked colima @('start')
        return
    }

    Fail 'Docker daemon não está rodando. Inicie o Docker Desktop ou o Colima antes de continuar.'
}

# ── Alvos ─────────────────────────────────────────────────────────────────────

$Alvos = [ordered]@{}

function Add-Target([string] $Name, [string] $Help, [scriptblock] $Action) {
    $Alvos[$Name] = [pscustomobject]@{ Help = $Help; Action = $Action }
}

Add-Target help 'Mostra este menu' {
    foreach ($nome in $Alvos.Keys) {
        Write-Host ('  {0,-16}' -f $nome) -ForegroundColor Cyan -NoNewline
        Write-Host $Alvos[$nome].Help
    }
}

# ── Start ──────────────────────────────────────────────────────────────────────
Add-Target up 'Build e sobe todos os serviços (foreground)' {
    Initialize-Env; Assert-Docker
    Invoke-Checked docker @('compose', 'up', '--build')
}

Add-Target up-d 'Build e sobe todos os serviços (background)' {
    Initialize-Env; Assert-Docker
    Invoke-Checked docker @('compose', 'up', '--build', '-d')
}

# ── Dev local com hot-reload ───────────────────────────────────────────────────
# Só as dependências rodam em container. A aplicação e o worker rodam no host com as
# credenciais do .env — nunca com usuário ou senha fixos no código.
Add-Target deps-up 'Sobe só banco, storage e Mailpit, com portas no host' {
    Initialize-Env; Assert-Docker
    Invoke-Checked docker (@('compose') + $ComposeDev + @('up', '-d') + $DevDeps)
}

Add-Target deps-down 'Para as dependências de dev' {
    Invoke-Checked docker (@('compose') + $ComposeDev + @('stop') + $DevDeps)
}

Add-Target watch-web 'Só a aplicação local em hot-reload (porta 5080)' {
    Initialize-Env; Import-DevEnv
    Invoke-Checked dotnet @('watch', 'run', '--project', 'src/OpenTube.Web')
}

Add-Target watch-worker 'Só o worker local em hot-reload' {
    Initialize-Env; Import-DevEnv
    Invoke-Checked dotnet @('watch', 'run', '--project', 'src/OpenTube.Worker')
}

Add-Target watch 'Dev completo: deps em container + aplicação e worker no host' {
    Initialize-Env; Assert-Docker
    Invoke-Checked docker (@('compose') + $ComposeDev + @('up', '-d') + $DevDeps)
    Import-DevEnv

    Write-Host ''
    Write-Host '  Aplicação →  http://localhost:5080   (dotnet watch)'
    Write-Host '  Worker    →  processo local'
    Write-Host '  Banco     →  localhost:5432   usuário e senha no .env'
    Write-Host '  MinIO     →  http://localhost:9000   console :9001   credenciais no .env'
    Write-Host '  Mailpit   →  http://localhost:8025'
    if ($env:Transcription__Executable) {
        $modelo = (Get-Item .whisper/modelo.bin).Target
        Write-Host "  Legendas  →  transcrição com Whisper$(if ($modelo) { ", modelo $modelo" })"
    } else {
        Write-Host "  Legendas  →  transcrição desligada ('./make.ps1 whisper' instala o Whisper e o modelo)"
    }
    Write-Host "  Ctrl+C encerra aplicação e worker. As deps seguem ('./make.ps1 deps-down' para pará-las)."
    Write-Host ''

    # Os dois no mesmo console, herdando as variáveis do .env. Ao sair, por Ctrl+C ou porque um
    # deles terminou, a árvore inteira de cada um é encerrada: o dotnet watch deixa filhos.
    $processos = @(
        Start-Process dotnet -ArgumentList 'watch', 'run', '--project', 'src/OpenTube.Web' -NoNewWindow -PassThru
        Start-Process dotnet -ArgumentList 'watch', 'run', '--project', 'src/OpenTube.Worker' -NoNewWindow -PassThru
    )

    try {
        while (-not ($processos | Where-Object HasExited)) {
            Start-Sleep -Milliseconds 500
        }
    } finally {
        foreach ($processo in $processos) {
            if (-not $processo.HasExited) {
                $processo.Kill($true)
            }
        }
    }
}

# Grava um catálogo de exemplo no banco do 'watch'. Sem argumento: 5 vídeos soltos e 5 coleções
# com 3 vídeos. -videos N muda os soltos. -collections N.M-K gera N coleções, cada uma com M a K
# vídeos. Compila em .artifacts/mock para não disputar bin/obj com o 'watch'. Rodar de novo
# substitui só os slugs que começam com mock-.
Add-Target mock 'Gera coleções e vídeos de teste  →  ./make.ps1 mock -videos 10 -collections 5.3-10' {
    Initialize-Env; Assert-Docker
    Invoke-Checked docker (@('compose') + $ComposeDev + @('up', '-d', '--wait') + $DevDeps)

    if (-not (Test-Command ffmpeg))  { Fail 'ffmpeg não está no PATH. Instale o FFmpeg antes do mock.' }
    if (-not (Test-Command ffprobe)) { Fail 'ffprobe não está no PATH. Ele acompanha o FFmpeg.' }

    Import-DevEnv

    $argumentos = @('run', '--project', 'src/OpenTube.Mock', '--artifacts-path', '.artifacts/mock', '--')
    if ($videos)      { $argumentos += @('--videos', $videos) }
    if ($collections) { $argumentos += @('--collections', $collections) }
    if ($colections)  { $argumentos += @('--collections', $colections) }

    Invoke-Checked dotnet $argumentos
}

# Instala o whisper.cpp e baixa o modelo usado pelo worker do 'watch', conferindo o SHA-256
# publicado. O modelo pode ser trocado: -m base (rápido) | small (melhor) |
# large-v3-turbo-q5_0 (o mais preciso).
Add-Target whisper "Liga a transcrição de legendas no watch  →  ./make.ps1 whisper -m base" {
    $modelo = if ($m) { $m } else { 'small-q5_1' }
    $origem = 'https://huggingface.co/ggerganov/whisper.cpp/resolve/main'

    # A mesma tabela que a imagem de produção usa. Um modelo fora dela é recusado: baixar sem
    # conferir seria aceitar qualquer arquivo com esse nome.
    $tabela = Get-Content docker/whisper/modelos.txt | Where-Object { $_ -notmatch '^\s*(#|$)' } |
        ForEach-Object { $c = -split $_; [pscustomobject]@{ Nome = $c[0]; Sha = $c[1] } }
    $sha = ($tabela | Where-Object Nome -eq $modelo).Sha

    if (-not $sha) {
        Fail "Modelo desconhecido: $modelo. Use um destes: $($tabela.Nome -join ' ')"
    }

    # ── Programa
    if (Test-Command whisper-cli) {
        Write-Host "  whisper-cli já instalado: $((Get-Command whisper-cli).Source)"
    } elseif (Test-Command brew) {
        Write-Host '  Instalando o whisper.cpp pelo Homebrew...'
        Invoke-Checked brew @('install', 'whisper-cpp')
    } else {
        Fail 'O whisper-cli não foi encontrado. Instale o whisper.cpp (https://github.com/ggml-org/whisper.cpp), ponha o whisper-cli no PATH e rode de novo.'
    }

    # ── Modelo
    New-Item -ItemType Directory -Force .whisper | Out-Null
    $arquivo = ".whisper/ggml-$modelo.bin"
    $confere = { param($caminho) (Test-Path $caminho) -and (Get-FileHash $caminho -Algorithm SHA256).Hash -eq $sha.ToUpperInvariant() }

    if (& $confere $arquivo) {
        Write-Host "  Modelo $modelo já baixado e conferido"
    } else {
        Write-Host "  Baixando o modelo $modelo..."
        $parcial = "$arquivo.parcial"
        Invoke-WebRequest "$origem/ggml-$modelo.bin" -OutFile $parcial -MaximumRetryCount 3

        if (-not (& $confere $parcial)) {
            Remove-Item $parcial -Force
            Fail 'O arquivo baixado não confere com o SHA-256 publicado; nada foi instalado.'
        }

        Move-Item $parcial $arquivo -Force
        Write-Host "  Modelo conferido: $arquivo"
    }

    # O modelo em uso tem um nome fixo, para o Import-DevEnv não precisar saber qual foi
    # escolhido. Link simbólico onde der; no Windows sem permissão para isso, um hard link.
    Remove-Item .whisper/modelo.bin -Force -ErrorAction SilentlyContinue
    try {
        New-Item -ItemType SymbolicLink -Path .whisper/modelo.bin -Target "ggml-$modelo.bin" | Out-Null
    } catch {
        New-Item -ItemType HardLink -Path .whisper/modelo.bin -Target $arquivo | Out-Null
    }

    Write-Host ''
    Write-Host "  Transcrição pronta com o modelo $modelo. Reinicie o './make.ps1 watch' para o worker usá-la."
}

# ── Stop ───────────────────────────────────────────────────────────────────────
Add-Target down 'Para e remove os containers' {
    Invoke-Checked docker @('compose', 'down')
}

Add-Target restart 'Reinicia um serviço sem rebuild  →  ./make.ps1 restart -s app' {
    Invoke-Checked docker (@('compose', 'restart') + @($s | Where-Object { $_ }))
}

# ── Observability ──────────────────────────────────────────────────────────────
Add-Target logs 'Segue logs (todos ou um serviço)  →  ./make.ps1 logs -s app' {
    Invoke-Checked docker (@('compose', 'logs', '-f') + @($s | Where-Object { $_ }))
}

Add-Target ps 'Lista containers e status' {
    Invoke-Checked docker @('compose', 'ps')
}

# ── Build ─────────────────────────────────────────────────────────────────────
Add-Target build 'Reconstrói as imagens sem subir' {
    Initialize-Env
    Invoke-Checked docker @('compose', 'build')
}

# ── Tests ─────────────────────────────────────────────────────────────────────
# Os testes de integração sobem Postgres e MinIO próprios (Testcontainers): precisam do Docker,
# mas não do .env nem das dependências do 'watch'. Os que usam FFmpeg são pulados quando ele não
# está instalado. Compilam em .artifacts/test, e não no bin/obj dos projetos, para não disputar
# arquivos com o 'watch' aberto.
Add-Target test 'Roda os testes  →  ./make.ps1 test  |  ./make.ps1 test -p Web  (Domain, Infrastructure, Worker, Web)' {
    Assert-Docker
    $alvo = if ($p) { "tests/OpenTube.$p.Tests" } else { 'OpenTube.slnx' }
    Invoke-Checked dotnet @('test', $alvo, '--artifacts-path', $TestArtifacts)
}

# ── License headers ───────────────────────────────────────────────────────────
# Todo arquivo de código leva o cabeçalho SPDX com licença e autoria; o CI recusa o que faltar.
Add-Target headers 'Acrescenta o cabeçalho de licença e autoria onde faltar (o CI confere)' {
    $python = @('python3', 'python', 'py') | Where-Object { Test-Command $_ } | Select-Object -First 1
    if (-not $python) {
        Fail 'Python 3 não encontrado no PATH.'
    }

    Invoke-Checked $python @('scripts/license-headers.py')
}

# ── Maintenance ───────────────────────────────────────────────────────────────
Add-Target clean 'Remove containers, volumes e orphans  (reset completo)' {
    Invoke-Checked docker @('compose', 'down', '-v', '--remove-orphans')
}

Add-Target shell 'Abre shell em um container em execução  →  ./make.ps1 shell -s app' {
    if (-not $s) {
        Fail 'Informe o serviço: ./make.ps1 shell -s app'
    }

    Invoke-Checked docker @('compose', 'exec', $s, 'sh')
}

# ── Execução ──────────────────────────────────────────────────────────────────
if (-not $Alvos.Contains($Target)) {
    Write-Host "  Alvo desconhecido: $Target" -ForegroundColor Red
    Write-Host ''
    & $Alvos['help'].Action
    exit 1
}

& $Alvos[$Target].Action
