// <auto-generated />
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Allan Barcelos. OpenTube: https://github.com/allanbarcelos/opentube

using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenTube.Infrastructure.Persistence;

#nullable disable

namespace OpenTube.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OpenTubeDbContext))]
    [Migration("20260930221904_MiniaturaDaColecao")]
    partial class MiniaturaDaColecao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenTube.Domain.Entities.AccessGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CanDownload")
                        .HasColumnType("boolean")
                        .HasColumnName("can_download");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<TimeSpan?>("DurationAfterFirstUse")
                        .HasColumnType("interval")
                        .HasColumnName("duration_after_first_use");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("FirstUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_used_at");

                    b.Property<Guid?>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<int?>("MaxViews")
                        .HasColumnType("integer")
                        .HasColumnName("max_views");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SealedToken")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sealed_token");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<int>("SubjectType")
                        .HasColumnType("integer")
                        .HasColumnName("subject_type");

                    b.Property<string>("SubjectValue")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("subject_value");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer")
                        .HasColumnName("target_type");

                    b.Property<int>("ViewsUsed")
                        .HasColumnType("integer")
                        .HasColumnName("views_used");

                    b.HasKey("Id")
                        .HasName("pk_access_grants");

                    b.HasIndex("InvitationId")
                        .HasDatabaseName("ix_access_grants_invitation_id");

                    b.HasIndex("RevokedAt")
                        .HasDatabaseName("ix_access_grants_revoked_at");

                    b.HasIndex("SubjectType", "SubjectValue")
                        .HasDatabaseName("ix_access_grants_subject_type_subject_value");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_access_grants_target_type_target_id");

                    b.ToTable("access_grants", (string)null);
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("action");

                    b.Property<string>("ActorEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("actor_email");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_hash");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("ActorEmail")
                        .HasDatabaseName("ix_audit_entries_actor_email");

                    b.HasIndex("At")
                        .HasDatabaseName("ix_audit_entries_at");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_entries_entity_type_entity_id");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.AuthAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("scope");

                    b.HasKey("Id")
                        .HasName("pk_auth_attempts");

                    b.HasIndex("Scope", "OccurredAt")
                        .HasDatabaseName("ix_auth_attempts_scope_occurred_at");

                    b.ToTable("auth_attempts", (string)null);
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_hash");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_sessions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_auth_sessions_expires_at");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("ix_auth_sessions_user_id_revoked_at");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<string>("ThumbnailKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("thumbnail_key");

                    b.Property<long>("ThumbnailVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("thumbnail_version");

                    b.HasKey("Id")
                        .HasName("pk_collections");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_collections_slug");

                    b.ToTable("collections", (string)null);
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.CollectionFavorite", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("CollectionId", "UserId")
                        .HasName("pk_collection_favorites");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_collection_favorites_user_id");

                    b.ToTable("collection_favorites", (string)null);
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.CollectionVideo", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("CollectionId", "VideoId")
                        .HasName("pk_collection_videos");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("ix_collection_videos_video_id");

                    b.ToTable("collection_videos", (string)null);
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<TimeSpan?>("DurationAfterFirstUse")
                        .HasColumnType("interval")
                        .HasColumnName("duration_after_first_use");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<int?>("MaxViews")
                        .HasColumnType("integer")
                        .HasColumnName("max_views");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_invitations_target_type_target_id");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.LoginCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("EmailDomain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("email_domain");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("GrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("grant_id");

                    b.Property<string>("IpHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_hash");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_login_codes");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_login_codes_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_login_codes_token_hash");

                    b.HasIndex("Email", "CreatedAt")
                        .HasDatabaseName("ix_login_codes_email_created_at");

                    b.ToTable("login_codes", (string)null);
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.PlaybackEvent", b =>
                {
                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Detail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("detail");

                    b.Property<double?>("FromSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("from_seconds");

                    b.Property<double>("Position")
                        .HasColumnType("double precision")
                        .HasColumnName("position");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<double?>("ToSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("to_seconds");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.HasKey("At", "Id")
                        .HasName("pk_playback_events");

                    b.ToTable("playback_events", (string)null);
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.PlaybackInterval", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("EndSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("end_seconds");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<double>("StartSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("start_seconds");

                    b.HasKey("Id")
                        .HasName("pk_playback_intervals");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_playback_intervals_session_id");

                    b.ToTable("playback_intervals", (string)null);
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.PlaybackSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnonymousId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("anonymous_id");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("browser");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean")
                        .HasColumnName("completed");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country");

                    b.Property<int>("Device")
                        .HasColumnType("integer")
                        .HasColumnName("device");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count");

                    b.Property<double>("FurthestPosition")
                        .HasColumnType("double precision")
                        .HasColumnName("furthest_position");

                    b.Property<Guid?>("GrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("grant_id");

                    b.Property<string>("IpHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_hash");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("MaxQuality")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("max_quality");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("operating_system");

                    b.Property<string>("Referrer")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("referrer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.Property<double>("WatchedSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("watched_seconds");

                    b.HasKey("Id")
                        .HasName("pk_playback_sessions");

                    b.HasIndex("GrantId")
                        .HasDatabaseName("ix_playback_sessions_grant_id");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_playback_sessions_last_seen_at");

                    b.HasIndex("UserId", "StartedAt")
                        .HasDatabaseName("ix_playback_sessions_user_id_started_at");

                    b.HasIndex("VideoId", "StartedAt")
                        .HasDatabaseName("ix_playback_sessions_video_id_started_at");

                    b.ToTable("playback_sessions", (string)null);
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.PlayerWatermark", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("image");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_player_watermark");

                    b.ToTable("player_watermark", null, t =>
                        {
                            t.HasCheckConstraint("ck_player_watermark_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.ProcessingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("locked_by");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("RunAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_after");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.HasKey("Id")
                        .HasName("pk_processing_jobs");

                    b.HasIndex("Kind", "TargetId")
                        .HasDatabaseName("ix_processing_jobs_kind_target_id");

                    b.HasIndex("Status", "RunAfter")
                        .HasDatabaseName("ix_processing_jobs_status_run_after");

                    b.ToTable("processing_jobs", (string)null);
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.SupportMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("FromAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("from_admin");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.HasKey("Id")
                        .HasName("pk_support_messages");

                    b.HasIndex("ThreadId", "CreatedAt")
                        .HasDatabaseName("ix_support_messages_thread_id_created_at");

                    b.ToTable("support_messages", (string)null);
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.SupportThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<DateTimeOffset?>("ReadByAdminAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_by_admin_at");

                    b.Property<DateTimeOffset?>("ReadByUserAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_by_user_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<double?>("TimestampSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("timestamp_seconds");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.HasKey("Id")
                        .HasName("pk_support_threads");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_support_threads_user_id");

                    b.HasIndex("Status", "LastMessageAt")
                        .HasDatabaseName("ix_support_threads_status_last_message_at");

                    b.HasIndex("VideoId", "UserId")
                        .HasDatabaseName("ix_support_threads_video_id_user_id");

                    b.ToTable("support_threads", (string)null);
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.TranscriptionWorker", b =>
                {
                    b.Property<string>("WorkerId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("worker_id");

                    b.Property<bool>("Available")
                        .HasColumnType("boolean")
                        .HasColumnName("available");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<string>("Engine")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("engine");

                    b.HasKey("WorkerId")
                        .HasName("pk_transcription_workers");

                    b.ToTable("transcription_workers", (string)null);
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("EmailDomain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("email_domain");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("EmailDomain")
                        .HasDatabaseName("ix_users_email_domain");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("HlsPrefix")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hls_prefix");

                    b.Property<string>("OriginalKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_key");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<string>("SpriteKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("sprite_key");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("ThumbnailKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("thumbnail_key");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("Transcript")
                        .HasColumnType("text")
                        .HasColumnName("transcript");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasColumnName("visibility");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.PrimitiveCollection<List<string>>("_tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.HasKey("Id")
                        .HasName("pk_videos");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_videos_created_at");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_videos_slug");

                    b.HasIndex("Visibility", "Status")
                        .HasDatabaseName("ix_videos_visibility_status");

                    b.ToTable("videos", (string)null);
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.VideoAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ContentUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("content_updated_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label");

                    b.Property<string>("Language")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.HasKey("Id")
                        .HasName("pk_video_assets");

                    b.HasIndex("VideoId", "Kind")
                        .HasDatabaseName("ix_video_assets_video_id_kind");

                    b.HasIndex("VideoId", "Language")
                        .IsUnique()
                        .HasDatabaseName("ux_video_assets_caption_language")
                        .HasFilter("kind = 0");

                    b.ToTable("video_assets", (string)null);
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.VideoChapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int>("StartSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("start_seconds");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.HasKey("Id")
                        .HasName("pk_video_chapters");

                    b.HasIndex("VideoId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_video_chapters_video_id_position");

                    b.ToTable("video_chapters", (string)null);
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.VideoDailyStat", b =>
                {
                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<int>("Completions")
                        .HasColumnType("integer")
                        .HasColumnName("completions");

                    b.Property<int>("UniqueViewers")
                        .HasColumnType("integer")
                        .HasColumnName("unique_viewers");

                    b.Property<int>("Views")
                        .HasColumnType("integer")
                        .HasColumnName("views");

                    b.Property<double>("WatchSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("watch_seconds");

                    b.HasKey("VideoId", "Day")
                        .HasName("pk_video_daily_stats");

                    b.HasIndex("Day")
                        .HasDatabaseName("ix_video_daily_stats_day");

                    b.ToTable("video_daily_stats", (string)null);
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.VideoRating", b =>
                {
                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("VideoId", "UserId")
                        .HasName("pk_video_ratings");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_video_ratings_user_id");

                    b.ToTable("video_ratings", null, t =>
                        {
                            t.HasCheckConstraint("ck_video_ratings_score", "score BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.VideoRetentionBucket", b =>
                {
                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.Property<int>("BucketIndex")
                        .HasColumnType("integer")
                        .HasColumnName("bucket_index");

                    b.Property<int>("Viewers")
                        .HasColumnType("integer")
                        .HasColumnName("viewers");

                    b.HasKey("VideoId", "BucketIndex")
                        .HasName("pk_video_retention_buckets");

                    b.ToTable("video_retention_buckets", (string)null);
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.AccessGrant", b =>
                {
                    b.HasOne("OpenTube.Domain.Entities.Invitation", null)
                        .WithMany()
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_access_grants_invitations_invitation_id");
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.CollectionFavorite", b =>
                {
                    b.HasOne("OpenTube.Domain.Entities.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_favorites_collections_collection_id");

                    b.HasOne("OpenTube.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_favorites_users_user_id");
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.CollectionVideo", b =>
                {
                    b.HasOne("OpenTube.Domain.Entities.Collection", null)
                        .WithMany("Videos")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_videos_collections_collection_id");
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.PlaybackInterval", b =>
                {
                    b.HasOne("OpenTube.Domain.Entities.PlaybackSession", null)
                        .WithMany("Intervals")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playback_intervals_playback_sessions_session_id");
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.SupportMessage", b =>
                {
                    b.HasOne("OpenTube.Domain.Entities.SupportThread", null)
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_support_messages_support_threads_thread_id");
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.VideoAsset", b =>
                {
                    b.HasOne("OpenTube.Domain.Entities.Video", null)
                        .WithMany("Assets")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_video_assets_videos_video_id");
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.VideoChapter", b =>
                {
                    b.HasOne("OpenTube.Domain.Entities.Video", null)
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_video_chapters_videos_video_id");
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.VideoRating", b =>
                {
                    b.HasOne("OpenTube.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_video_ratings_users_user_id");

                    b.HasOne("OpenTube.Domain.Entities.Video", null)
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_video_ratings_videos_video_id");
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.Collection", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.PlaybackSession", b =>
                {
                    b.Navigation("Intervals");
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.SupportThread", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("OpenTube.Domain.Entities.Video", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
