#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Allan Barcelos. OpenTube: https://github.com/allanbarcelos/opentube

# Generate .env with a random user, password, and keys. If the file already
# exists, leave it alone: PostgreSQL only accepts the password from the first
# initialization of the volume.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
dest="${root}/.env"

if [[ -f "$dest" ]]; then
  echo "  .env already exists — credentials kept."
  exit 0
fi

command -v openssl >/dev/null 2>&1 || { echo "openssl is required to generate the credentials." >&2; exit 1; }

secret() {
  openssl rand -base64 64 | tr -d '/+=\n' | head -c "$1"
}

umask 077
cat > "$dest" <<EOF
# Generated by scripts/gen-env.sh. Do not commit.
POSTGRES_DB=db_$(openssl rand -hex 5)
POSTGRES_USER=user_$(openssl rand -hex 4)
POSTGRES_PASSWORD=$(secret 32)
MINIO_ROOT_USER=minio_$(openssl rand -hex 4)
MINIO_ROOT_PASSWORD=$(secret 32)
TOKEN_PEPPER=$(secret 48)
IP_HASH_PEPPER=$(secret 48)
OPENTUBE_HOST=localhost
OPENTUBE_ADMIN_EMAIL=${OPENTUBE_ADMIN_EMAIL:-admin@localhost}
EOF
chmod 600 "$dest"

echo "  .env created with a random user, password, and keys."
echo "  The file stays on this machine only (mode 600). It is not printed again."
