#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Allan Barcelos. OpenTube: https://github.com/allanbarcelos/opentube

"""
Cabeçalho de licença e autoria em todo arquivo de código do projeto.

    python3 scripts/license-headers.py           acrescenta onde falta
    python3 scripts/license-headers.py --check   só confere (o CI usa); sai com erro se faltar

Vale para os arquivos versionados no git. Código de terceiros (wwwroot/lib) e o que veio
pronto do modelo de projeto da Microsoft ficam de fora: não são deste projeto.
"""

import subprocess
import sys
from pathlib import Path

LINHAS = [
    "SPDX-License-Identifier: MIT",
    "Copyright (c) 2026 Allan Barcelos. OpenTube: https://github.com/allanbarcelos/opentube",
]

MARCA = "SPDX-License-Identifier:"

# Código de terceiros, ou gerado pelo modelo de projeto, que não leva o cabeçalho deste projeto.
IGNORADOS = (
    "src/OpenTube.Web/wwwroot/lib/",
    "src/OpenTube.Web/Components/Layout/ReconnectModal.razor",
)

# Extensão (ou nome de arquivo) → como comentar.
LINHA = {".cs": "// {}", ".js": "// {}", ".sh": "# {}", ".py": "# {}", ".yml": "# {}", ".yaml": "# {}"}
BLOCO = {
    ".css": ("/*", " * {}", " */"),
    ".razor": ("@*", "    {}", "*@"),
    ".csproj": ("<!--", "  {}", "-->"),
    ".props": ("<!--", "  {}", "-->"),
    ".slnx": ("<!--", "  {}", "-->"),
}
NOMES = {"Dockerfile": "# {}", "Makefile": "# {}", "Caddyfile": "# {}"}


def estilo(caminho: Path):
    if caminho.name in NOMES:
        return ("linha", NOMES[caminho.name])
    if caminho.suffix in LINHA:
        return ("linha", LINHA[caminho.suffix])
    if caminho.suffix in BLOCO:
        return ("bloco", BLOCO[caminho.suffix])
    return None


def cabecalho(tipo, formato) -> str:
    if tipo == "linha":
        return "\n".join(formato.format(l) for l in LINHAS) + "\n"
    abre, meio, fecha = formato
    return "\n".join([abre, *(meio.format(l) for l in LINHAS), fecha]) + "\n"


def arquivos():
    saida = subprocess.run(["git", "ls-files"], capture_output=True, text=True, check=True).stdout
    for nome in saida.splitlines():
        if nome.startswith(IGNORADOS):
            continue
        caminho = Path(nome)
        if caminho.exists() and estilo(caminho):
            yield caminho


def tem_cabecalho(texto: str) -> bool:
    return any(MARCA in linha for linha in texto.splitlines()[:8])


def acrescentar(caminho: Path, texto: str) -> str:
    tipo, formato = estilo(caminho)
    bom = "﻿" if texto.startswith("﻿") else ""
    corpo = texto[len(bom):]
    linhas = corpo.splitlines(keepends=True)

    # Linhas que precisam continuar em primeiro: o shebang dos scripts, a declaração XML e o
    # aviso de código gerado (o EF e os analisadores o procuram no começo do arquivo).
    preservar = 0
    if linhas and (
        linhas[0].startswith("#!")
        or linhas[0].startswith("<?xml")
        or "<auto-generated" in linhas[0]
    ):
        preservar = 1

    antes = "".join(linhas[:preservar])
    depois = "".join(linhas[preservar:])
    separador = "" if depois.startswith("\n") else "\n"

    return bom + antes + cabecalho(tipo, formato) + separador + depois


def main() -> int:
    conferir = "--check" in sys.argv[1:]
    faltando = []

    for caminho in arquivos():
        texto = caminho.read_text(encoding="utf-8")
        if tem_cabecalho(texto):
            continue
        faltando.append(caminho)
        if not conferir:
            caminho.write_text(acrescentar(caminho, texto), encoding="utf-8")

    if conferir:
        if faltando:
            print("Arquivos sem o cabeçalho de licença e autoria:")
            for caminho in faltando:
                print(f"  {caminho}")
            print("\nRode: python3 scripts/license-headers.py  (ou make headers)")
            return 1
        print("Todos os arquivos têm o cabeçalho de licença e autoria.")
        return 0

    print(f"Cabeçalho acrescentado em {len(faltando)} arquivo(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
